raws:
    Metadata: "sample_info.csv"

parameters:
    Study: "ERP104047"
    # Input_dir: "./"
    Pride_id: "PXD003791"
    Version: "5.0"
    Db_size: 1073741824
    ThermoFold: "input/Raw"
    first_name: "Shengbo"
    last_name: "Wang"
    email: "shengbo_wang@ebi.ac.uk"
    address: "EBI"
    org_name: "EBI"
    org_email: "test@ebi.ac.uk"
    org_address: "Cambridge"
outputdir: "./"
workdir: "./"
tmpdir: "./tmp"
output:
    searchgui_folder: "searchgui"
    peptideshaker_folder: "peptideshaker"
thermo:
    url: "https://github.com/compomics/ThermoRawFileParser/releases/download/{version}/ThermoRawFileParser.zip"
    exe: "ThermoRawFileParser.exe"
    version: "v1.2.3"
searchgui:
    url: "http://genesis.ugent.be/maven2/eu/isas/searchgui/SearchGUI/{version}/SearchGUI-{version}-mac_and_linux.tar.gz"
    jar: "SearchGUI-{version}/SearchGUI-{version}.jar"
    version: "3.3.20"
    par:
        prec_tol: 10
        prec_ppm: 1
        frag_tol: 0.02
        frag_ppm: 0
        digestion: 0
        enzyme: "Trypsin"
        specificity: 0
        mc: 2
        fixed_mods: "Carbamidomethylation of C"
        variable_mods: "Oxidation of M"
        min_charge: 2
        max_charge: 4
        fi: "b"
        ri: "y"
        min_isotope: 0
        max_isotope: 1
        import_peptide_length_min: 6
        import_peptide_length_max: 50
        xtandem_noise_suppr: 0
        xtandem_quick_acetyl: 1
        xtandem_quick_pyro: 1
        xtandem_refine: 1
        msgf_instrument: 1
        msgf_fragmentation: 1
        msgf_protocol: 0
        msgf_min_pep_length: 6
        msgf_max_pep_length: 50
        msgf_num_ptms: 2
        comet_num_ptms: 3
peptideshaker:
    url: "http://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/{version}/PeptideShaker-{version}.zip"
    jar: "PeptideShaker-{version}/PeptideShaker-{version}.jar"
    version: "1.16.45"
